# -*- coding: utf-8 -*-
"""Task - 01

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12O2COl40gngP5R0f5hvvGcBw9LP1UAKq
"""

import pandas as pd

# Step 1: Create the sample dataset
data = {
    "Age Group": ["0–20 Years", "21–64 Years", "65+ Years"],
    "Population (in Millions)": [512, 807, 98],
    "Percentage": [36.1, 57.0, 6.9]
}

df = pd.DataFrame(data)

# Step 2: Save the dataset as a CSV file
df.to_csv("population_by_age.csv", index=False)

print("✅ CSV file 'population_by_age.csv' created!")
df
# Load the CSV file into a DataFrame
df = pd.read_csv("population_by_age.csv")

print("✅ Dataset Loaded:")
df
import matplotlib.pyplot as plt

# Bar chart from dataset
plt.figure(figsize=(8, 6))
bars = plt.bar(df["Age Group"], df["Population (in Millions)"], color=["gold", "dodgerblue", "hotpink"])

# Add text labels
for bar, pct in zip(bars, df["Percentage"]):
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, height + 10,
             f"{height} Mn\n({pct}%)", ha='center', fontsize=11)

# Chart formatting
plt.title("India's Population Distribution by Age Group (2022)", fontsize=14)
plt.ylabel("Population (in Millions)")
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()